# Generated by Django 3.2.7 on 2021-09-20 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_auto_20210920_1517'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostImages',
        ),
    ]
